Feature/navigation 네비게이션 추가
NOW-SOPT-APP1-YeogiEottae/YeogiEottae-Android pull request #12
Opened 2024-05-13 09:21 UTC by cacaocoffee

## 🧑🏻‍💻작업 내용
- #11 
>  네비게이션 초기세팅했습니다.

## 구현화면

2024-05-13 10:08 UTC, 0se0 requested changes
수고많으셨습니다~!
(저희 커밋 컨벤션도 다시 한번 확인해주심 좋을 거 같아요~!!)

2024-05-13 10:08 UTC, 0se0 commented on app/src/main/res/drawable/ic_favorite.xml
> +      android:pathData="M11.5,20C11.252,20 11.008,19.955 10.769,19.866C10.531,19.776 10.306,19.632 10.096,19.433L8.406,17.821C6.325,15.891 4.487,14.005 2.892,12.164C1.297,10.323 0.5,8.318 0.5,6.149C0
코드 정렬 필요할 거 같아요! 색상도 color에 지정되어 있는 것으로 바꿔주면 어떨까요??

2024-05-13 10:08 UTC, 0se0 commented on app/src/main/res/drawable/ic_home.xml
> +      android:pathData="M2.5,20C1.813,20 1.224,19.776 0.735,19.329C0.245,18.881 0,18.343 0,17.714V9.429C0,9.067 0.089,8.724 0.266,8.4C0.443,8.076 0.688,7.81 1,7.6L8.5,0.457C8.729,0.305 8.969,0.19 9.2
여기두 코드 정렬 필요할 거 같아요! 색상도 color에 지정되어 있는 것으로 바꿔주면 어떨까요??

2024-05-13 10:08 UTC, 0se0 commented on app/src/main/res/drawable/ic_info.xml
> +      android:fillColor="#999999"/>
여기두 코드 정렬 필요할 거 같아요! 색상도 color에 지정되어 있는 것으로 바꿔주면 어떨까요??

2024-05-13 10:08 UTC, 0se0 commented on app/src/main/res/drawable/ic_map.xml
> +      android:fillColor="#999999"/>
여기두 코드 정렬 필요할 거 같아요! 색상도 color에 지정되어 있는 것으로 바꿔주면 어떨까요??

2024-05-13 10:08 UTC, 0se0 commented on app/src/main/res/drawable/ic_search.xml
> +      android:fillColor="#999999"/>
ㅎㅎ여기두 코드 정렬 필요할 거 같아요! 색상도 color에 지정되어 있는 것으로 바꿔주면 어떨까요??

2024-05-13 10:08 UTC, 0se0 commented on app/src/main/res/drawable/menu_selector_color.xml
> +</selector>
체고

2024-05-13 10:08 UTC, 0se0 commented on app/src/main/java/com/sopt/yeogieottae/MainActivity.kt
> +        binding.bnvHome.setupWithNavController(navController)
```suggestion
       val navHostFragment = supportFragmentManager.findFragmentById(R.id.nav_host_fragment) as NavHostFragment
        val navController = navHostFragment.navController
        binding.bnv.setupWithNavController(navController)
```

오 이렇게도 할 수 있군여!! 저는 이렇게 써요!👍👍
(그냥 얘기한거에요ㅋㅎㅋㅎ)

2024-05-13 10:08 UTC, 0se0 commented on app/src/main/res/layout/activity_main.xml
> +        android:id="@+id/nav_host_fragment"
여기 아이디 fragmentcontainerview에 맞는 아이디로 해보는 건 어떨까용? main_fcv 혹은 fcv 이렇게요!

2024-05-13 10:08 UTC, 0se0 commented on app/src/main/res/layout/activity_main.xml
> +        android:layout_height="match_parent"
0dp, 0dp로 맞추고 constraint 설정해주면 좋을 거 같아요!

2024-05-13 10:08 UTC, 0se0 commented on app/src/main/res/layout/activity_main.xml
> +        android:id="@+id/bnv_home"
home화면이랑은 또 다르니까 main_bnv 혹은 bnv 이렇게 이름 짓는 건 어떠실지요!!

2024-05-13 10:08 UTC, 0se0 commented on app/src/main/res/menu/menu_bottom_navigation.xml
> +        android:enabled="true"
오 요런건 저도 첨봐서.. 어떤걸까요??

2024-05-13 11:22 UTC, cacaocoffee commented on app/src/main/res/layout/activity_main.xml
> +        android:id="@+id/bnv_home"
엇 그렇네요.. 이름 짓는 걸 좀 더신경써봐야겠어요

2024-05-13 11:22 UTC, cacaocoffee commented on app/src/main/res/layout/activity_main.xml
> +        android:layout_height="match_parent"
넵 수정했습니다!

2024-05-13 11:22 UTC, cacaocoffee commented on app/src/main/res/drawable/ic_search.xml
> +      android:fillColor="#999999"/>
넵 위코드들과 함꼐 정렬 및 색상 변경했습니다.

2024-05-13 13:04 UTC, 0se0 approved these changes
수고 많으셨습니다~!!!

2024-05-13 13:04 UTC, 0se0 commented on app/src/main/res/navigation/nav_graph.xml
> +            app:destination="@id/fragment_hotel" />
`action_search_to_hotel` 요렇게 하면 더 편할 거 같아요!

2024-05-13 13:08 UTC, 0se0 commented on app/src/main/res/navigation/nav_graph.xml
> +        tools:layout="@layout/fragment_room" />
여기 각 프래그먼트마다 한 줄 씩 띄워주면 더 보기 좋을 거 같아요!

2024-05-14 03:48 UTC, cacaocoffee commented on app/src/main/res/menu/menu_bottom_navigation.xml
> +        android:enabled="true"
엇 여기 답글 달았었는데 사라졌네요 
checked는 현재 체크 상태를 의미하구 
enabled는 클릭가능, 불가능을 정해주는 요소로 알고있어요
enabled는 삭제하고 시작점을 home으로 설정했습니다.

2024-05-14 03:48 UTC, cacaocoffee commented on app/src/main/res/navigation/nav_graph.xml
> +        tools:layout="@layout/fragment_room" />
넵! 처리했습니다

2024-05-14 03:49 UTC, cacaocoffee commented on app/src/main/res/navigation/nav_graph.xml
> +            app:destination="@id/fragment_hotel" />
넵 수정했어요!

2024-05-14 04:17 UTC, merged