Feature/like
NOW-SOPT-APP1-YeogiEottae/YeogiEottae-Android pull request #18
Opened 2024-05-17 12:09 UTC by 2hyunjinn

## 👩🏻‍💻작업 내용
- #15 

## 구현화면

https://github.com/NOW-SOPT-APP1-YeogiEottae/YeogiEottae-Android/assets/95455569/32b6acee-83c8-45cf-a1b3-a6e2ea2701a2

## 이슈

## 기타

2024-05-20 12:53 UTC, cacaocoffee approved these changes
가볍게 봤어요 수고하셨습니다.

2024-05-20 12:53 UTC, cacaocoffee commented on app/src/main/res/drawable/shape_circle.xml
> +</shape>
여기 부분은 shapeImgaview를 통해 사용하면서 shapeAppearance로 줄수 있어요

2024-05-20 12:53 UTC, cacaocoffee commented on app/src/main/java/com/sopt/yeogieottae/ui/like/LikeFragment.kt
> +
```suggestion
  private fun showPopup() {
    // 애니메이션 팝업에 적용
    val animation = AnimationUtils.loadAnimation(requireContext(), R.anim.bottom_sheet_anim)
    binding.loLikePopupBottom.startAnimation(animation)

    // 팝업을 표시
    binding.loLikePopup.visibility = View.VISIBLE
}

```

2024-05-20 12:53 UTC, cacaocoffee commented on app/src/main/java/com/sopt/yeogieottae/ui/search/SearchViewHolder.kt
> +    @SuppressLint("RestrictedApi")
여기 노테이션 필수로 들어가야하는건가요?

2024-05-20 12:53 UTC, cacaocoffee commented on app/src/main/java/com/sopt/yeogieottae/ui/like/FavoriteHotelListAdapter.kt
> +    @SuppressLint("NotifyDataSetChanged")
ListAdatpter로 써보는건 어때요?

2024-05-20 13:04 UTC, 0se0 requested changes
수고하셨습니다!!!

2024-05-20 13:04 UTC, 0se0 commented on app/src/main/java/com/sopt/yeogieottae/data/Like/FavoriteHotel.kt
패키지명은 소문자로 바꾸는 게 좋을 거 같아요!

2024-05-20 13:04 UTC, 0se0 commented on app/src/main/java/com/sopt/yeogieottae/ui/like/LikeFragment.kt
> +    private val binding get() = _binding!!
확장함수로 만들어놓은 basefragment 적용해보면 좋을 거 같아요!

2024-05-20 13:04 UTC, 0se0 commented on app/src/main/java/com/sopt/yeogieottae/ui/like/FavoriteHotelListAdapter.kt
> +        notifyDataSetChanged()
시간 남으면 diffutil 활용해봐도 좋을 거 같아용

2024-05-20 13:04 UTC, 0se0 commented on app/src/main/java/com/sopt/yeogieottae/ui/like/FavoriteHotelListAdapter.kt
> +    @SuppressLint("NotifyDataSetChanged")
이 어노테이션은 어떤 건가요??

2024-05-20 13:04 UTC, 0se0 commented on app/src/main/java/com/sopt/yeogieottae/ui/like/FavoriteHotelViewHolder.kt
> +        }
대박!!👍👍

2024-05-20 13:04 UTC, 0se0 commented on app/src/main/java/com/sopt/yeogieottae/ui/like/LikeFragment.kt
> +            layoutManager = LinearLayoutManager(context)
xml 상에서 linearlayoutmanager 설정해볼 수도 있을 거 같아요!!

2024-05-20 13:04 UTC, 0se0 commented on app/src/main/java/com/sopt/yeogieottae/ui/search/SearchFragment.kt
> +    private val binding get() = _binding!!
여기도 basefragment 확장함수 사용해보면 좋을 거 같아요!

2024-05-20 13:04 UTC, 0se0 commented on app/src/main/res/drawable/bg_date.xml
코드 정렬 해야할 거 가탕요!

2024-05-20 13:04 UTC, 0se0 commented on app/src/main/res/drawable/ic_calendar.xml
여기두 정렬해야 할 거 같아요!

2024-05-20 13:04 UTC, 0se0 commented on app/src/main/res/layout/item_favorite_hotel.xml
ㅜㅜ 이거 시간남으면 constraintlayout으로 고쳐봅시당!!

2024-05-22 09:53 UTC, 0se0 approved these changes
수고 많으셨습니다~!!👍👍

2024-05-22 09:53 UTC, 0se0 commented on app/src/main/java/com/sopt/yeogieottae/data/like/LikeService.kt
> +    ): Call<ResponseLikeHotelDto>
헤더 인터셉터로 바꿔보면 좋을 거 같아용

2024-05-22 10:51 UTC, merged